FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:10-buster-build as build

RUN npm install --unsafe-perm -g cncjs

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:10-buster

COPY --from=build /usr/local /usr/local

EXPOSE 8000

RUN mkdir /config

CMD /usr/local/bin/cncjs -H 0.0.0.0 -p 8000 -c /config/cncrc
